<script
      src="assets/css/boostrap.min.css"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
    ></script>
  </body>
</html>
<?php
include('./head.php');
?>